apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: sprind-boot containers
          image: vinodo3735/newbuild:v1
          ports:
            - containerPort: 8080
